name: consulta_cep
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  search_cep: ^4.0.1
  brasil_fields: ^1.4.1
  map_launcher: ^2.4.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/background-map.png


  fonts:
    - family: FormulaCondensed
      fonts:
          - asset: assets/fonts/formulaCondensed/FormulaCondensed-Regular.ttf
            weight: 400
          - asset: assets/fonts/formulaCondensed/FormulaCondensed-Black.ttf
            weight: 900
          - asset: assets/fonts/formulaCondensed/FormulaCondensed-Bold.ttf
            weight: 700
          - asset: assets/fonts/formulaCondensed/FormulaCondensed-Light.ttf
          - asset: assets/fonts/formulaCondensed/FormulaCondensed-Ultralight.ttf
    - family: MonumentExtended
      fonts:
            - asset: assets/fonts/monumentExtended/MonumentExtended-Regular.ttf
            - asset: assets/fonts/monumentExtended/MonumentExtended-Bold.ttf
            - asset: assets/fonts/monumentExtended/MonumentExtended-Light.ttf
            - asset: assets/fonts/monumentExtended/MonumentExtended-Regular.ttf
            - asset: assets/fonts/monumentExtended/MonumentExtended-Ultrabold.ttf
            - asset: assets/fonts/monumentExtended/MonumentExtended-Ultralight.ttf